---

- hosts: servers
  become: true
  pre_tasks:


  - name: install updates(Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: install updated(CentOS)
    tags: always
    dnf:      
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS" 

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEC8aw/cvvarHjkoNh4hTEhVHGef9ANMtdnoomOabDq7 Ansible"

- hosts: workstation
  become: true
  tasks:
 
  - name: install unzip on work station
    package:
      name: unzip
   
  - name:  install terraform on worksation
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root 


- hosts: webservers
  become: true
  tasks:


  - name: install apache2 and php packages
    tags: apache2,mod-php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php package in CentOS
    tags: httpd,php,centOs
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd(CentOS)
    tags: apache,apache2,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: chane email for admin
    tags: apache,apache2,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.donf
      regxp: '^ServerAdmin'
      line: ServerAdmin Someone@hotmail.com
    when: ansible_distribution == "CentOS" 
    register: httpd

  - name: restart httpd(CentOs)
    tags: apache,apache2,httpd
    service:
      name: httpd 
      state: restarted
    when: httpd.changed

  - name: copy defaullt files to site
    tags: apache2,mod-php,ubuntu,cpFiles
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
