---

- hosts: servers
  become: true
  tasks:

  - name: update repo
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php suport for apache(install php suport) only if its a ubuntu distrubution
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: update repo in centOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: install apache2 package in CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" 

  - name: add php suport for apache(install php suport) only if its a CentOS distrubution
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
