---

- hosts: servers
  become: true
  pre_tasks:


  - name: install updates(Ubuntu)
    tags: always
    apt:
      updrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: install updated(CentOS)
    tags: always
    dnf:
      update_only: yes      
      update_cache: yes
    when: ansible_distribution == "CentOS" 


- hosts: webservers
  become: true
  tasks:


  - name: install apache2 and php packages
    tags: apache2, mod-php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php package in CentOS
    tags: httpd, php, centOs
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
