- name: install unzip on work station
  package:
    name: unzip

- name:  install terraform on worksation
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
