- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3N2zaCz1NTE5AAAAIEC8aw/cvvdareHjkoNh4hTBrEhVHGef9ANMtdnoomOabDq7 Ansible"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh
