- name: install apache2 and php packages ubuntu/centOs
  tags: apache2,httpd,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: enable and start apache services
  tags: apache,apache2,httpd
  service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

- name: chane email for admin
  tags: apache,apache2,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.donf
    regxp: '^ServerAdmin'
    line: ServerAdmin Someone@hotmail.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache


- name: copy defaullt files to site
  tags: apache2,mod-php,ubuntu,cpFiles
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
